name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    steps:
      - uses: actions/checkout@v4
      
      # pnpmを使用する場合
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'  # npmの代わりにpnpmを指定
          
      - name: Install dependencies
        run: pnpm install  # npm ciの代わりにpnpm install
        
      - name: Run lint
        run: pnpm run lint
        
      - name: Run type check
        run: pnpm run typecheck
        
      - name: Run tests
        run: pnpm test
        
      - name: Build
        run: pnpm run build